### ISSUE TITLE
Higher resolution

### ISSUE THREAD

**Issue by Arrerong** [carson-katri/dream-textures#152]
Hi! Amazing tool! I've tried my way with how high I can set the resolution, and the limit for my machine seems to be 1023x1023. If I try 1024x1024 it simply lags for a few seconds and then doesn't do anything. Since that is exactly 4x the resolution of 512x512 I'm thinking that that probably isn't a coincidence, but maybe rather a "set" limit? Is there a way to change this to be able to set it to higher resolutions? I realize that it's probably because of my computer's limits, but maybe there's a way to tell it to run anyway and just do it much slower or something? 'Cos I'd be fine with it taking much longer, as long as I get higher resolution

**Comment by SolusGod** [comment]
I believe it's because of your VRAM limit on your GPU. I don't think it's possible for it to run a higher resolution without a VRAM Increase. I have a GeForce 1060 with 6g VRAM and I can only do 512, anything other than that and Blender hangs for a sec or two and nothing happens.

**Comment by Arrerong** [comment]
Ah fair enough! I might have to invest in a new graphics card then.. Cheers!

**Comment by SolusGod** [comment]
In upcoming versions I saw that there will be an Image upscale function so wait and see!

**Comment by RazorWolvendom** [comment]
yeah same here with my RTX 2070 S having 8GB Vram only could run like 959x959 max for some reason

**Comment by Xelgardi** [comment]
I too ran into this and tested a few things. It seems that only the dedicated GPU memory gets properly used and only a fraction of the shared memory gets any attention. 

To be more specific: I'm running a RTX3070 with 8GB dedicated VRAM and have a total of 32GB RAM. That gets me 15,9GB of shared GPU memory for a grand total of 23,9GB RAM usable to my GPU. And yet the highest shared memory usage I saw was 1,2GB for about 9GB total. And that was with a resolution of 1152x1152. Anything higher resulted in a "not enough memory" error. 
With nearly 13GB or about 55% of VRAM to spare I think that's not quite how it should be.

**Comment by SolusGod** [comment]
Interesting point. I wonder if Stable Diffusion can make use of the Shared GPU Memory. That would save me the trouble of getting a new Card :D

**Comment by RazorWolvendom** [comment]
yeah i dont really want to save up 2k for a Quadro RTX 5000 tbh, they should add also maybe like a function to generate the image in Divisons / splits so like partially 1/4 or 1/8 so it doesnt has to load that much at once,

so like rendering one 512x512 and extends it by 2 in Width and Height so that it processes 4 times the same resolution to get the higher resolution as result of 1024x1024 etc if thats even worth it

**Comment by mattiabruni** [comment]
Not the original author but I spent some time playing around with the reference implementations of Stable Diffusion.

While a setting to use less memory does exist somewhat it is a real pain to set up. 
Also SD is made to have at least one dimension be exactly 512; while it can produce bigger resolutions it would actually be repeating parts of the same image and "loosing coherence" (AKA giving possibly nonsensical results).
Therefore x4 upscaling is likely the better option in most cases. (this also makes for faster iterations so that you can then upscale only the images you actually like)

**Comment by RazorWolvendom** [comment]
> Not the original author but I spent some time playing around with the reference implementations of Stable Diffusion.
> 
> While a setting to use less memory does exist somewhat it is a real pain to set up. Also SD is made to have at least one dimension be exactly 512; while it can produce bigger resolutions it would actually be repeating parts of the same image and "loosing coherence" (AKA giving possibly nonsensical results). Therefore x4 upscaling is likely the better option in most cases. (this also makes for faster iterations so that you can then upscale only the images you actually like)

ok good, then we have to wait for the upscale feature ig

**Comment by mattiabruni** [comment]
BTW I use waifu2x-extension-gui to do ESRGAN upscale with little setup needed and 4GB of VRAM is more than enough for that.
It does take a while though and it disrupts the workflow somewhat so I only do it for images I've committed to.

**Comment by MrGTAmodsgerman** [comment]
A alternative option of being abe to use a cloud computer service or some sort of for the task, would cover a lot of the hardware issues.

**Comment by Harvester62** [comment]
@carson-katri Since the subject of this report was about higher resolution image generation, and the author @Arrerong seemed to recognize that the issue might be lack of VRAM on his graphics card, I think this cannot be considered a BUG per se. Therefore, I would suggest to close this report, so to clean-up the list of bug reports.
