### ISSUE TITLE
Seed is not saved in history

### ISSUE THREAD

**Issue by Fry2412** [carson-katri/dream-textures#161]
When using the history list, I would actually expect to get exactly the same image as the prompt.  
Thus, saving the seed of the respective pass of a prompt in the history would be a nice convenience feature.

I might be able to add a pull request in a few days.

**Comment by carson-katri** [comment]
It should be saving the seed after it receives the final image. If you can figure out the bug that’d be great.

**Comment by Xelgardi** [comment]
@carson-katri Where should the seed be saved? The history doesn't even have a column for it. The image node does get named with the seed number though. Running version 0.0.6
On a similar note: The same seed with the same settings should result in the exact same result, doesn't it? If so, there might be yet another bug, because I get different results even if I re-run with the same seed as previously.

**Comment by Fry2412** [comment]
I mean that in the prompt the '-1' should be exchanged with the seed. This way you have the exact same starting point to create an image.
![image](https://user-images.githubusercontent.com/7856444/192758019-b2bfff1f-12c6-48c6-b15a-89f4b0c1ca61.png)


But with that, I noticed another problem.
The assigned seed is not accepted by the mask at all as it is (see screenshots).

![image](https://user-images.githubusercontent.com/7856444/192759216-bd8f1c37-7622-4f65-9ce7-3d69b288bd7c.png)
![image](https://user-images.githubusercontent.com/7856444/192759229-a533e198-e7f3-40c8-858c-b87d01846727.png)

**Comment by carson-katri** [comment]
This is fixed in version 0.0.6. And although it does not show the seed in the table, every parameter is stored in the history.
