### ISSUE TITLE
Internal error, received image of wrong resolution 320x512, expected 512x512

### ISSUE THREAD

**Issue by lonedfx** [carson-katri/dream-textures#192]
The new version(0.0.6) is giving errors when using the Init Image option with an image that isn't of the target dimension, regardless of whether the Fit to width/height option is selected:

For a 512x512 texture:
Internal error, received image of wrong resolution 320x512, expected 512x512 (with Fit to width/height)
Internal error, received image of wrong resolution 704x1024, expected 512x512 (without Fit to width/height)

I now have to select the size of the input image as the size of the texture by hand. That's not such a big deal obviously, but this was working fine in 0.0.5 without having to do so.

**Comment by Silven88** [comment]
If your output is set to 512 x 512, and your source image resolution is 1024 x 2048, the error message will read "received image of wrong resolution 256x512, expected 512x512. 

This is telling you to set your output resolution to 256x512 in order to maintain the same aspect ratio as your source image. It works as long as you adjust your output resolution accordingly.

**Comment by lonedfx** [comment]
@Silven88 thank you for your input, but no this is an actual regression, see my original message which clearly indicates that what worked in 0.0.5 no longer works in 0.0.6. In fact, the issue has already been fixed as part of revision #204, which is part of 0.0.7 milestone:

https://github.com/carson-katri/dream-textures/pull/204

"Fixes regression https://github.com/carson-katri/dream-textures/issues/192. The error check that is causing that regression has been swapped for a similar one that doesn't have expectations based on user input width and height."

**Comment by carson-katri** [comment]
Closing as fixed in #204
