### ISSUE TITLE
local language support (i18n)

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [carson-katri/dream-textures#223]
Would you finish it in the future?

**Comment by NaughtDZ** [comment]
Local language support  may depends on whether the model training is supported or not, not this plug-in.

**Comment by carson-katri** [comment]
Are you referring to translating the model, or translating the addon ui?

**Comment by BUGProtectionAssociation** [comment]
> Are you referring to translating the model, or translating the addon ui?

ui translate of course. And how to support more model than one.
Because addon only support a model file named model right now...

**Comment by carson-katri** [comment]
I’d accept contributions to add localization, but I only speak English so I can’t add it myself

**Comment by Harvester62** [comment]
Hi Carson Katri, I am currently curating the Italian localization of Stable Diffusion Web UI by AUTOMATIC1111, updating the User Interface, the Scripts and Extensions (it's a work in progress due to the fast pace of the developers to add features into it). Would you like me to do the same for your Blender add-on? 

The localization on SDWUI is done via a json file (localization.json is the template's file name defaulting to English language, and all the localization files are placed inside a \localizations folder as it_IT.json, by example). Would you be able to take the same approach? Best regards.

**Comment by Harvester62** [comment]
Hi @carson-katri , this is just to keep this report active. In the meantime, I worked on the UI translation of InvokeAI, in case it might be of interest, and got a supervising role too. The InvokeAI Project is now using Weblate (https://weblate.org) as the platform for the localization, in case you might be interested in.
