### ISSUE TITLE
Please make prompt text field bigger

### ISSUE THREAD

**Issue by vtushevskiy** [carson-katri/dream-textures#239]
Please make prompt text field bigger - several strings, not one

**Comment by carson-katri** [comment]
I'm not sure I understand. Do you mean the text should wrap to multiple lines?

**Comment by vtushevskiy** [comment]
Yes multiple lines text field that contain long prompt textOn Oct 4, 2022, at 14:50, Carson Katri ***@***.***> wrote:﻿
I'm not sure I understand. Do you mean the text should wrap to multiple lines?

**Comment by RazorWolvendom** [comment]
> I'm not sure I understand. Do you mean the text should wrap to multiple lines?

i mean he could just drag out the border to see the line further but he means like being able to set a "Enter" for multiple lines just like in any text programms without having to do the separations with "|" for example

**Comment by difreo** [comment]
Agree, last update was great but changing long prompts still is a pain :) multiline is the way to go

**Comment by JasonHoku** [comment]
I found a pretty hacky way to edit prompts with multi-line capability.

Right click the prompt and select Copy Full Data Path, then enter the Blender Scripting tab, add import bpy on the first line and paste the path in on the second followed by = and then wrap your text in triple double quotes `"""` like so:

```py
import bpy

bpy.data.scenes["Scene"].dream_textures_prompt.prompt_structure_token_subject = """
X
Y
Z
"""
```

Finally, run the script and mouse over the ui to run the draw update call.

Viola! Multi-line text editing of prompts within Blender.

You can also add `bpy.ops.shade.dream_texture()` to the last line of the script and render your prompts with the hotkey Alt + P from the scripting menu with this setup.

Maybe adding a right click option to automate most of that could be nice since the Blender UI seems to not support any simple method for multi-line text input nor text wrapping.
