### ISSUE TITLE
Suggestion:  Add relevant settings (e.g. Prompt, Seed, Strength, CFG, etc.) to the image metadata

### ISSUE THREAD

**Issue by realstevewarner** [carson-katri/dream-textures#275]
It would be extremely helpful to have the pertinent info used to generate an image stored in the image's metadata.  This would include the Prompt text, Seed, CFG, Strength (if using Init), etc.  One of the standalone SD implementations saves out this info as a text file alongside the image.  That's useful, but storing the info in the image metadata is even more helpful and efficient.

Thanks for the consideration!

**Comment by carson-katri** [comment]
We have the JSON export now in 0.0.7. I know invoke ai does some image metadata embedding, I’ll just need to figure out how blender’s API handles it.

**Comment by realstevewarner** [comment]
Thanks for the consideration.  It looks like Blender can add a custom note for metadata, which would seem like a natural place to store DT info.  However if DT isn't running things through the native Blender renderer, I'm not sure how difficult it would be to access that.  Maybe now that it can run through Cycles as a render pass it will be easier?  Again, appreciate you considering this!

**Comment by GottfriedHofmann** [comment]
Afaik there is no Python API in Blender for editing image metadata yet, the notes are created only for rendered images.

**Comment by JasonHoku** [comment]
The SD Webui by AUTOMATIC1111 has a couple similar features that might be relevant here:

The aesthetic-image-scorer addon makes use of tags and meta data:
https://github.com/tsngo/stable-diffusion-webui-aesthetic-image-scorer/blob/main/tools/add_tags.py

And the images-browser addon can read, search and sort by tags and meta data:
https://github.com/yfszzx/stable-diffusion-webui-images-browser/blob/main/scripts/images_history.py

Though it was a requirement for the aesthetic scorer (but not images-browser) to setup a 3rd party software (I used File Meta) to enable tags on PNG files, however images-browser was storing and reading nearly all relevant meta data without any 3rd party software or tags. 

Though, according to https://docs.blender.org/manual/en/latest/files/media/image_formats.html it looks like PNGs have native meta data support within blender so that may be a cleaner route.

And a bit more research shows that exif data is a potential python solution: https://pypi.org/project/exiv2/
