### ISSUE TITLE
Cycles Render Pass not showing up

### ISSUE THREAD

**Issue by UglyStupidHonest** [carson-katri/dream-textures#295]
I have everything wired up in the comp nodes but I only get a transparent image somehow after the images is rendered
the console gives me this : 
"bpy_prop_array[slice] = value: re-sizing bpy_struct element in arrays isn't supported"

resolution is : 512x512

Thank you so much for all your work this is amazing :) 

**System (please complete the following information):**
- OS
  - [x] Windows
  - [ ] macOS
  - [ ] Other
- GPU
  - [x] NVIDIA
  - [ ] NVIDIA 16*XX*
  - [ ] Apple Silicon
  - [ ] AMD
- Addon Version
  - Latest

**Comment by monday1313** [comment]
First of all, thanks for this add-on...really great work!

I have the same problem as the OP with the last message in the terminal exactly the same as the OP's. 
Blender 3.3.0 with python 3.10.2
MacOS 12.6
  Model Name:	Mac Pro
  Model Identifier:	MacPro7,1
  Enclosure:	Tower
  Processor Name:	12-Core Intel Xeon W
  Processor Speed:	3.3 GHz
  Number of Processors:	1
  Total Number of Cores:	12
  L2 Cache (per Core):	1 MB
  L3 Cache:	19.3 MB
  Hyper-Threading Technology:	Enabled
  Memory:	96 GB

Dream Textures 0.0.7

I tried using both GPU and CPU, still get transparent image. I also tried with Render Properties/  Film / Transparent set to on and off.

**Comment by jeffmorice** [comment]
I had a similar problem when attempting to use this addon with an older blend file. After comparing a working file and the non-working file, I found that the working file had the Z pass unchecked. To resolve, try going to Properties > View Layer Properties tab > Passes > Data and unchecking the Z pass.

Beware though, I just experienced a blue screen when attempting to render 10+ images in a row, due to VRAM management.
