### ISSUE TITLE
There is no current event loop  loop = asyncio.get_event_loop() error.

### ISSUE THREAD

**Issue by TheD3vilHimself** [carson-katri/dream-textures#35]
Trying to run Dream Texture on Blender 3.3 on windows and get the following from the Terminal:

"...AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\async_loop.py:62: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()"
  
  Fresh install and installed as Admin.

**Comment by nimbold** [comment]
I did the same and get the same results.

Error log:

`TypeError: CLIPTokenizer.__init__() missing 1 required positional argument: 'merges_file'
C:\Users\XXXX\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\async_loop.py:62: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()`

GTX 1650
Run as admin/ fresh install

**Comment by drag0nD** [comment]
i have the same error and same gpu i think its a problem with 16xx gpus not supporting half precision its even mentions in https://rentry.org/voldy

"If you get a green/black output instead of generated pictures, you have a card that doesn't support half precision floating point numbers (known problem on 16xx cards):
-edit webui-user.bat
-Modify line 6 to COMMANDLINE_ARGS=--precision full --no-halfalong with any other flags you wish to add
Unfortunately, the model will take much more space in VRAM-
So it is recommended to use flags like --medvram in combination with it"

but enabling full precision will cause VRAM errors because 1650 has 4 GB RAM

**Comment by TheD3vilHimself** [comment]
Running it on 2070 RTX with 8GB here. 
Noticed that out of nowhere a node to the Normals that is Tangent Normal gets plugged but nothing else happens.

**Comment by drag0nD** [comment]
> Oh, so this seems to be the problem. Nice catch! Yeah, sadly, GTX 1650 has 4 GB VRAM. I'll try the `--medvram` with it in different tries to see if it works.

is that possible with this addon? that solution was for the web app not this addon

**Comment by nimbold** [comment]
> > Oh, so this seems to be the problem. Nice catch! Yeah, sadly, GTX 1650 has 4 GB VRAM. I'll try the `--medvram` with it in different tries to see if it works.
> 
> is that possible with this addon? that solution was for the web app not this addon

I thought it can be done with editing some files, but seems like I don't have the knowledge yet.

**Comment by carson-katri** [comment]
I’m not sure what that medvram option is, but it is not supported by this addon. For 16XX cards you will need to run with full precision enabled and likely reduce the size of your generated image.

**Comment by carson-katri** [comment]
@TheD3vilHimself the deprecation warning is not the actual error. Please either post the full output or try to find an error that is not related to the asyncio deprecation.

**Comment by alexandis** [comment]
I've installed this plugin on my old notebook HP EliteBook 8540W having NVidia Quadro FX 880M videocard. I've run the simplest texture generation which indicated in the manual (512x512 brick wall). After a while, I see the following output in the console (the texture is of course not generated):
[render_issue.txt](https://github.com/carson-katri/dream-textures/files/9610144/render_issue.txt)

**Comment by TheD3vilHimself** [comment]
> I've installed this plugin on my old notebook HP EliteBook 8540W (manufactured in 2005 or something :)) having NVidia Quadro FX 880M videocard. I've run the simplest texture generation which indicated in the manual (512x512 brick wall). After a while, I see the following output in the console (the texture is of course not generated): [render_issue.txt](https://github.com/carson-katri/dream-textures/files/9610144/render_issue.txt) I wonder if I should created a separate issue for my case. I want to make this plugin work, no matter if I should wait longer for the texture generation.

At least you managed to  get the first part of the error. On my end, it gets buried because the buffer is overtaken by the repetitive error warnings.

@carson-katri I've tried to launch the process to see the error but it always gets buried.

**Comment by drag0nD** [comment]
> I’m not sure what that medvram option is, but it is not supported by this addon. For 16XX cards you will need to run with full precision enabled and likely reduce the size of your generated image.

i tried generating 4x4 texture it still show memory error.

**Comment by PAN-CHRZAN** [comment]
Is there any way to run arguments through dream textures scripts? I'm not afraid to modify them but dunno where to start.
Yes, I unfortunately have a 1660 and can't make it work (even with the full precision option enabled) even with 16x16px:l

**Comment by carson-katri** [comment]
@PAN-CHRZAN Heres where it creates the generator: https://github.com/carson-katri/dream-textures/blob/b6e786164dfb202e4625ba926dffa898d1374a54/operators/dream_texture.py#L65
And here’s where it runs it: https://github.com/carson-katri/dream-textures/blob/b6e786164dfb202e4625ba926dffa898d1374a54/operators/dream_texture.py#L146

**Comment by PAN-CHRZAN** [comment]
It's too much, can't figure out what the web-ui version author did that makes it work on my gpu, I can just confirm that in his version the medvram option does the trick.

**Comment by emeraldminer299** [comment]
@drag0nD Might where I find the webui-user.bat in the addon directory? It seems hidden away.

**Comment by Filip2002avramovic** [comment]
I have the same issue on GeForce RTX 3050 Ti Laptop with 4GB dedicated

**Comment by alexandis** [comment]
So is there an explanation why texture generation is getting failed? I'm not a Python programmer, so I don't understand from that log output what's going on and what do I do to make it work... ;)

**Comment by mbendele** [comment]
> I unfortunately have a 1660 and can't make it work (even with the full precision option enabled) even with 16x16px:l

I have 1660ti and was using small values for width and height and low number of steps to try and make it work for me. Turns out that the width and height must be mult of 64, so my early tests were not generating images at all and not giving obvious error as to why. Maybe try minimum image size of 64x64 px. Otherwise, I updated my main installation of Python to newest ver, installed new Blender 3.3, updated NVidia drivers, and I'm using Full Precision flag in addon as noted above with other settings at default.

**Comment by PAN-CHRZAN** [comment]
It's not gonna work in usable resolution without the vram optimization that's in the [web-ui](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Optimizations) interface for Stable Diffusion. Specifically you need at least the --medvram flag enabled to make SD work on 1660. With the flag I can make the web-ui SD spit out 512 images no problem, without it it's either black image or just an error about pytorch eating up most of the ram.

Unfortunately the flag (or commandline argument) itself is not something you can just pass to dream-textures and make it work because the optimization is not implemented here. I was trying to figure out what the flag does but it's too much for my puny brain so I just stick to web-ui until I get myself a decent card. You can make seamless textures in there just as well.

**Comment by alexandis** [comment]
So do I get it right that the probable fix for this issue will be available in version 0.0.6?
