### ISSUE TITLE
🧨 diffusers Backend

### ISSUE THREAD

**Issue by carson-katri** [carson-katri/dream-textures#399]
I am considering replacing InvokeAI with a simple HuggingFace diffusers pipeline. In fact, InvokeAI is working on rewriting their internals to use diffusers itself, and simply providing different interfaces and extensions off it.

Benefits of diffusers:
* Simpler build process - it's just another package, not a submodule
* More control over the pipeline
* Lighter backend - InvokeAI has a lot more bloat than when this project was initially created
* Cleaner code base - InvokeAI is based on the original CompVis code, which is honestly kind of a mess. Diffusers has a much simpler structure making it easier to extend and reason about.
* Access to more SOTA diffuser models - diffusers is not limited to just SD, so other models could be used in the future.
* Optimizations - when I first created this add-on I chose InvokeAI for their platform support and optimizations. Now, diffusers seems to have them beat in optimizations with configuration to get under 2GB of memory
* AMD support via ONNX - I personally won't be able to test this, but it presumably works and could be included fairly easily

Benefits of sticking with InvokeAI:
* No code changes needed here
* Any features and optimizations they build on top of diffusers we get for free - arguably, these should be contributed to diffusers, but 🤗 seems to prefer readability over performance to some extent
* Maintaining custom pipelines - for example, we will need to maintain the code that enables seamless generation, and other patches that are currently handled by InvokeAI

I'm leaning towards going for it. But I'd like to get some thoughts before I move forward.

**Comment by rexorp** [comment]
Although I have moved on to using sd-web-ui, I say go for it. Especially considering the benefits. Cheers! Sent from Mail for Windows From: Carson KatriSent: Thursday, November 17, 2022 5:53 AMTo: carson-katri/dream-texturesCc: SubscribedSubject: [carson-katri/dream-textures] 🧨 diffusers Backend (Issue #399) I am considering replacing InvokeAI with a simple HuggingFace diffusers pipeline. In fact, InvokeAI is working on rewriting their internals to use diffusers itself, and simply providing different interfaces and extensions off it.Benefits of diffusers:Simpler build process - it's just another package, not a submoduleMore control over the pipelineLighter backend - InvokeAI has a lot more bloat than when this project was initially createdCleaner code base - InvokeAI is based on the original CompVis code, which is honestly kind of a mess. Diffusers has a much simpler structure making it easier to extend and reason about.Access to more SOTA diffuser models - diffusers is not limited to just SD, so other models could be used in the future.Optimizations - when I first created this add-on I chose InvokeAI for their platform support and optimizations. Now, diffusers seems to have them beat in optimizations with configuration to get under 2GB of memoryAMD support via ONNX - I personally won't be able to test this, but it presumably works and could be included fairly easilyBenefits of sticking with InvokeAI:No code changes needed hereAny features and optimizations they build on top of diffusers we get for free - arguably, these should be contributed to diffusers, but 🤗 seems to prefer readability over performance to some extentMaintaining custom pipelines - for example, we will need to maintain the code that enables seamless generation, and other patches that are currently handles by InvokeAII'm leaning towards going for it. But I'd like to get some thoughts before I move forward.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
