### ISSUE TITLE
not generating

### ISSUE THREAD

**Issue by Aadi100409** [carson-katri/dream-textures#437]
### Description

hi
when i click generate it just says "starting..." and doesn't do anything.

version: 0.0.9

### Steps to Reproduce

1. install addon
2. go to image editor
3. enter prompt
4. click generate

### Expected Behavior

the image would generate in a span of time

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by dasparadoxon** [comment]
yeah. I have the same problem. It worked once after installing it and trying it after restart, but only produced black images.

now it is always stuck on "Starting..." 

in the dos command window there is an error : 

Exception in thread Thread-33 (_send_thread):
Traceback (most recent call last):
  File "D:\...\Blender 3.4\3.4\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\...\Blender 3.4\3.4\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 299, in _send_thread
    response = self._response_queue.get()
  File "D:\...\Blender 3.4\3.4\python\lib\multiprocessing\queues.py", line 122, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'torch'

Version : 0.0.9
1660 Ti 6GB

(version 0.0.8 works perfect for me with full precision)

**Comment by Aadi100409** [comment]
ty. i'll try 0.0.8

**Comment by C-InfDef** [comment]
Any luck?

**Comment by Aadi100409** [comment]
no  :(

**Comment by Aadi100409** [comment]
i found the issue. i don't have enough memory even though i have 12gb ram

**Comment by dasparadoxon** [comment]
thats when you do not make a mesh object with a material assigned to it.

just create a plane and add a material to it.

**Comment by Aadi100409** [comment]
k i'll try it and get back

**Comment by Aadi100409** [comment]
didn't work pls help me carson

**Comment by JasonHoku** [comment]
> didn't work pls help me carson

Hmm. A few questions that might get to the bottom of this:

What version of blender are you on? (A minimum version of 3.1 is required, alpha/beta versions might not work)

What type of GPU do you have? (Older and low vram gpu's may not be supported to run locally)

Have you tried a completely fresh installation of Blender? (There are some known issues with updating DT that are resolved with a clean Blender install)

According to this issue report, which shares your error message https://github.com/carson-katri/dream-textures/issues/388 it could be caused by a bad (maybe interrupted or corrupted) model installation. Maybe wiping your huggingface folder and re-installing the model through the addon model installer might fix your issue.

It could also help to get a full copy paste of your Blender Console error message.

**Comment by jurassicjordan** [comment]
I'm having the same issue, only happens in the image viewer. if I do a depth generation in the viewport it works just fine, everywhere else is completely broken. (endoeavourOS, nvidia, blender 3.4.1)
