### ISSUE TITLE
OSError('/home/jordancruz/.config/blender/3.3/scripts/addons/dream_textures/.python_dependencies/torch/lib/libtorch_global_deps.so: cannot open shared object file: No such file or directory')

### ISSUE THREAD

**Issue by jurassicjordan** [carson-katri/dream-textures#463]
**Is your feature request related to a problem? Please describe.**
I hate to be that guy, but the install instructions for Linux are very unclear. when setting up from the repo the addon denies me unless I use the latest release.

**Describe the solution you'd like**
can you please, for all of us Open source software lovers, make the install instructions a little more in depth?

**Describe alternatives you've considered**
better yet a can we please get a dedicated Linux release with .so instead of .dll files for the dependancies? Thank you.

**Comment by noneoftheaboves** [comment]
I agree , not a lot of information for linux users...this is how far i got...
Clone and update the Github file...put the dream_textures in the blender addon folder.
Install addon and import the weights. 

But then the last part witch take me about 5 hour...4.Install dependencies locally ???

when i push generate i get the following..

blender/3.2/scripts/addons/dream_textures/.python_dependencies/torch/lib/libtorch_global_deps.so: cannot open shared object file: No such file or directory')

The .python_dependencies folder is empty exept for a file: gitignore ??

Seem i have a problem writing to this location..In the terminal a lot of errors pop up in yellow..

WARNING target directory ROOT/..../dream_textures/.python_dependencies/pyasn1 already exists. Specify --upgrade to force replacement.

Since this code is generated by blender there is no way for me to add --upgrade to anything. Also like i said these files are not at that location. I run Blender as an admin from the terminal and i open the folder as admin. ..

Anyone Any idea on how to get those files in that location..(pip dependencies for the selected platform into .python_dependencies)

Happy NY
