### ISSUE TITLE
Stable diffusion V2.1 Wont install on Mac :/

### ISSUE THREAD

**Issue by Matt4tanka** [carson-katri/dream-textures#608]
### Description

When I try installing the model: Stable diffusion V2.1, it doesn't even start to download and just stays at 0%. Ive tried re-installing and I'm using blender 3.4.1, really confused why its not working, dunno if its just my MAC, any help would be great :)

### Steps to Reproduce

-

### Expected Behavior

-

### Addon Version

macOS (Apple Silicon)

### GPU

Apple Silicon

**Comment by jialulu123** [comment]
the same problem, and there is no tutorial for macbook

**Comment by nenhures** [comment]
<img width="661" alt="Screenshot 2023-04-24 at 16 38 44" src="https://user-images.githubusercontent.com/131692906/234047784-a1cf9a7d-dc32-41e7-aaba-9509c485db7e.png">

Same problem here. I think it might be related with some of the latest Mac OS update, because a few weeks ago I didn't have this problem. Today, when trying to install dream-texture's 2.0 version, these warnings appeared for the first time.

<img width="260" alt="Screenshot 2023-04-24 at 16 36 07" src="https://user-images.githubusercontent.com/131692906/234047834-56ad6169-d959-4c49-a32a-99a043ffb862.png">
<img width="259" alt="Screenshot 2023-04-24 at 16 38 10" src="https://user-images.githubusercontent.com/131692906/234047842-07bf227c-bb10-4dbe-a2c4-304de8e44e27.png">

I installed dream-texture 1.0 and the exact same thing happened. When the addon was loaded these two warnings appeared, and afterwards, when trying to install stable diffusion, it locked on 0% like OP mentioned.
My OS is Ventura 13.0.1.
