### ISSUE TITLE
"No model selected" only when a model is selected

### ISSUE THREAD

**Issue by WeatherWonders** [carson-katri/dream-textures#763]
### Description

In the image editor, when no model is selected (as in a new scene) in the "Dream Texture" section, there is no warning saying "no model selected". When I select a model, the warning appears and the "generate" button is still disabled, even after I click the X next to it.

v0.2 didn't have this issue, and the upscaler section works fine (except that you have to click the X twice initially to enable the "generate" button). Downloading a model or turning the add-on off and back on again fixes the issue until Blender is restarted.

### Steps to Reproduce

1. Ensure the add-on is enabled and a model has been downloaded (e.g. the recommended stabilityai ones).
2. Restart Blender.
3. Go to the "Dream" tab in the image editor.
4. Set "Model" at the top to any option.

### Expected Behavior

"No model selected" would appear with the drop-down to select one when dream_textures_prompt.model is an empty string, and would disappear and allow clicking "generate" when that property is a non-empty string (or, ideally, a model name).

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by yoyoyeahyoyo** [comment]
in the meantime, i found that if i close the dream texture tab, and toggle the plugin from disabled to enabled in edit->preferences, that resets that start button and it works again. so seems like a simple UI bug. im on linux with amd gpu

**Comment by agosch** [comment]
I have the same problem on Windows 11 with Blender 4.0.

**Steps to reproduce:**

1. Install Add-On and complete Setup
2. Restart Blender
3. Try to create a new texture, and after a model is selected it will tell you that "No model selected"

**Add-On version:** 0.3.1 CUDA (Windows)

**GPU:** NVidia RTX 4090

The workaround form @yoyoyeahyoyo works for me.

**Comment by Luciijfea** [comment]
I'm using **Windows 10** x64 with Blender 4.0.2 and also got the same bug.
**Add-On version:** 0.3.1 CUDA (Windows)
**GPU:** NVIDIA GeForce RTX 2070 Super

Now while I did not find a real solution, I did make the Workaround a little shorter by editing 
_%APPDATA%\Roaming\Blender Foundation\Blender\4.0\scripts\addons\dream_textures\\_ **diffusers_backend.py**

Instead of raising _FixItError()_ I simply:
``` Python
265        if model is None:
267            pass
268            #raise FixItError("No model selected.", FixItError.ChangeProperty("model"))
269        else:
270                ...
```
This way, instead of going into settings and unloading/reloading the AddOn, all you have to do is click on "Release Generator" (X to the right of the "► Generate"-Button)

**Comment by ThaNoodles** [comment]
Hello, I have same problem in M1 Max Pro. "no model selected" every time I try to use it.

Copy paste description and steps because is the same). Work around is similar as just rechecking the addon though sometimes it doesn't work.

Description
In the image editor, when no model is selected (as in a new scene) in the "Dream Texture" section, there is no warning saying "no model selected". When I select a model, the warning appears and the "generate" button is still disabled, even after I click the X next to it.

Steps to Reproduce
Ensure the add-on is enabled and a model has been downloaded (e.g. the recommended stabilityai ones).
Restart Blender.
Go to the "Dream" tab in the image editor.
Set "Model" at the top to any option.

Expected Behavior
"No model selected" would appear with the drop-down to select one when dream_textures_prompt.model is an empty string, and would disappear and allow clicking "generate" when that property is a non-empty string (or, ideally, a model name).
