### ISSUE TITLE
<title>Why was this bug created？

### ISSUE THREAD

**Issue by zhongweijian-svg** [carson-katri/dream-textures#775]
### Description

[](url)
![Screenshot 2024-02-26 112917](https://github.com/carson-katri/dream-textures/assets/118967857/da4f6008-6494-46b0-ae61-33fd374019aa)
![Screenshot 2024-02-26 112858](https://github.com/carson-katri/dream-textures/assets/118967857/e3ee7f3c-3a17-42a9-bf2c-aea6d6ff6435)
just this

### Steps to Reproduce

3.3 and 4.0 had texted

### Expected Behavior

A solution

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by GeminiSquishGames** [comment]
If you get the "ModuleNotFoundError" the remedy is to delete the dream textures folder where Blender keeps add-ons and manually open the zip file and drop the dream_textures folder there instead, rather than have Blender try and install it from its menu. 

In your case I see an inconsistency. Your first image shows you are using D:\game\steamapps\common\Blender\4.0\scripts\modules...
However, your second screen shot is showing that it's using D:\tool\blender\3.3\scripts\modules...

This could be the problem you are having. You may need to uninstall or delete where Blender is now and do a bit of housekeeping. I suggest using the .msi files from Blender.org instead of Steam or using .zip files to install Blender. Then when you have the version of Blender you want to use installed from the .msi setup app, manually drop the dream_texures folder from the plugins .zip file to %APPDATA%/Roaming\Blender Foundation\Blender\4.0\scripts\addons\
